version: "3.9"

services:
  backend:
    build: ./backend
    container_name: code_editor-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always
    # network_mode: "host" # optional - only for Linux users
